#!/bin/bash
################################################################################
#
#  Program:  scan-services-check.sh
#  Function: Check Tomcat/Documentum services on all active lower environments.
#            Restart any services that are not running.
#
#-------------------------------------------------------------------------------
# MODIFICATION HISTORY
#
#  When        Who             Why
# ------------------------------------------------------------------------------
#  2023-02-06  E. Duffy        Original version.
#  2023-02-07  E. Duffy        Changes to mail format for clarity.
#
################################################################################

# Set up some essential variables.
DR="N"
ThisScript=$(realpath $0)
ThisHost=$(hostname)
EmailSuffix="\n\n________________________________________________________________________________\nFor troubleshooting purposes, this email was generated by the following script: ${ThisHost}:${ThisScript}."
RestartText=""

echo "Checking the status of Scanning services in the lower environments..."

# We will perform the check on all the current active non-Prod environments.
for Environment in "RM PP2" "RM QA2" "OMR PP2" "OMR QA1" "OMR QA2" "ICR PP2" "ICR QA1"
# For testing, comment out the line above and uncomment the line below. Switch them back when done.
#for Environment in "ICR PP2"
do

# Find the names of the app and content servers for the environment we're dealing with.
   . subroutines/scan-environment-setup.sh $Environment

#  Check the content servers.
   for i in "${!content_servers[@]}"
   do
      content_server=${content_servers[$i]}
      cs_location=$(echo ${content_server_locations[$i]} | tr [:lower:] [:upper:])
      echo "Checking content server status on $content_server..."
      if ! ssh -qn $content_server "su - dmadmin -c './dctmContentServer status'" | grep -q "Content Server is active"
      then
         echo "The content server is NOT running. Will restart."
         RestartText="${RestartText}    ${Environment} content server $content_server\n"
         echo "First we will kill any orphaned Documentum processes..."
         ssh -qn $content_server "ps -fudmadmin | sed '1d' | egrep 'documentum|docbase' | awk '{ print \$2 }' | xargs -r kill -9"
         echo "Now clearing the Documentum cache folder..."
         ssh -qn $content_server "su - dmadmin -c 'rm -rf \$DOCUMENTUM/cache/*'"
         echo "Starting Documentum services..."
         ssh -qn $content_server "su - dmadmin -c 'timeout 3m ./dctmContentServer start || echo ERROR - Command timed out.'"
      fi
   done

#  Check the application servers.
   for i in "${!app_servers[@]}"
   do
      app_server=${app_servers[$i]}
      app_location=$(echo ${app_server_locations[$i]} | tr [:lower:] [:upper:])
      echo "Checking tomcat status on $app_server..."
      if ! ssh -qn $app_server "systemctl status tomcat | grep -q 'Active: active'"
      then
         echo "Tomcat is NOT running. Will restart."
         RestartText="${RestartText}    ${Environment} application server $app_server\n"
         echo "First we will kill any orphaned Tomcat processes..."
         ssh -qn $app_server "ps -futomcat | sed '1d' | egrep 'jsvc' | awk '{ print \$2 }' | xargs -r kill -9"
         echo "Now clearing the Tomcat cache folders..."
         ssh -qn $app_server "rm -rf /opt/tomcat/work/* /opt/tomcat/temp/* /opt/tomcat/bin/documentum/cache/* /opt/documentum/cache/*"
         echo "Starting Tomcat service..."
         ssh -qn $app_server "timeout 3m systemctl start tomcat || echo ERROR - Command timed out."
      fi
   done
done
if [ -z "$RestartText" ]
then
   echo "All good - no restarts were done."
else
#  Restarts were performed. Mail details about what was restarted to the appropriate people.
   printf "Services were found to be down on the following servers. All were restarted.\n\n${RestartText}${EmailSuffix}" |\
   mail -s "The Scanning lower environments check found some stopped services and restarted them." \
gowri.jaya@cambridge.org Preethika.Dhanabal@cambridge.org chagantipati.s@cambridgeassessment.org.uk saipriya.tingirkar@cambridge.org shubham.saurabh@cambridge.org someshwar.ranga@cambridge.org tharaka.chemakurthi@cambridge.org senthilkumar.a@cambridgeassessment.org.uk eddie.duffy@cambridge.org
# For testing, comment out the line above and uncomment the line below. Switch them back when done.
#gowri.jaya@cambridge.org saipriya.tingirkar@cambridge.org eddie.duffy@cambridge.org
fi

printf "\nAll done.\n"
